### ISSUE TITLE
When force_types=None used, strings with numeric values are changed to ints

### ISSUE THREAD

**Issue by vpavlin** [bkabrda/anymarkup#3]
IIUC this code should provide basically the same input regarding value types.

```
import anymarkup

data = anymarkup.parse_file("file.json", force_types=None)
anymarkup.serialize_file(data, "output.json")
```

But if you feed this file into it:
http://pastebin.centos.org/27686/
you'll get this:
http://pastebin.centos.org/27691/

The change can be seen in `env` object:
```
"env":[
                { "name": "SERVER_ID", "value": "1" }
              ],
```
which changes to
```
"env": [
                {
                  "name": "SERVER_ID",
                  "value": 1
                }
              ],
```
Which then fails to load by openshift/kubernetes parser as it expects `value` to be a string. I tried to do the same with plain `json.load/json.dump` and it preserves types correctly.

**Comment by bkabrda** [comment]
Fixed and released: https://pypi.python.org/pypi/anymarkup/0.4.1

Thanks for the report!
