### ISSUE TITLE
PyPI package doesn't include test/__init__.py

### ISSUE THREAD

**Issue by encukou** [bkabrda/anymarkup#4]
When I download the tarball on PyPI, the tests won't run:

    test/test_parse.py:13: in <module>
        class TestParse(object):
    test/test_parse.py:34: in TestParse
        (example_ini, example_as_dict),
    E   NameError: name 'example_ini' is not defined

**Comment by bkabrda** [comment]
Fixed and uploaded to PyPI as version 0.4.2: https://pypi.python.org/packages/source/a/anymarkup/anymarkup-0.4.2.tar.gz
