### ISSUE TITLE
RFE: json5

### ISSUE THREAD

**Issue by hroncok** [bkabrda/anymarkup#8]
It would be nice if anymarkup could load json5.

> JSON5 is a proposed extension to JSON that aims to make it easier for humans to write and maintain by hand. It does this by adding some minimal syntax features directly from ECMAScript 5.

https://github.com/json5/json5
Implementation for Python: https://pypi.python.org/pypi/json5

**Comment by bkabrda** [comment]
Makes sense, I'll implement this when I get some more free time. Thanks for the suggestion.

**Comment by bkabrda** [comment]
Fixed by https://github.com/bkabrda/anymarkup/commit/d3e68736c5ff4276563f5644dbf95fde0cc42029 and https://github.com/bkabrda/anymarkup-core/commit/e7097477a428becde97c5b2d5410bb99d61df3a1

Closing. Enjoy!

**Comment by hroncok** [comment]
Thank you.
